pipeline {
    agent {
        docker {
            image 'docker:24.0.7'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        IMAGE_NAME = "python-demo"
        IMAGE_TAG  = "v1"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                    docker build -t ${IMAGE_NAME}:${IMAGE_TAG} docker-demo-python/
                """
            }
        }

        stage('Test Run Container') {
            steps {
                sh """
                    # Start container WITHOUT exposing port 5000
                    docker run --rm -d --name python-test ${IMAGE_NAME}:${IMAGE_TAG}

                    # Wait for app to start
                    sleep 3

                    # Test inside container instead of localhost
                    docker exec python-test curl -s http://localhost:5000

                    # Stop container
                    docker stop python-test
                """
            }
        }

        stage('Trivy Scan') {
            steps {
                sh """
                    docker run --rm \
                        -v /var/run/docker.sock:/var/run/docker.sock \
                        aquasec/trivy:latest \
                        image ${IMAGE_NAME}:${IMAGE_TAG}
                """
            }
        }

        stage('List Images') {
            steps {
                sh "docker images | grep ${IMAGE_NAME}"
            }
        }
    }
}
