pipeline {
    agent {
        docker {
            image 'docker:24.0.7'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        IMAGE_NAME = "python-demo"
        IMAGE_TAG  = "v1"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                    docker build -t ${IMAGE_NAME}:${IMAGE_TAG} docker-demo-python/
                """
            }
        }

        stage('Test Run Container') {
    steps {
        sh """
            # Force remove old container if exists
            docker rm -f python-test || true

            # Start new container
            docker run -d --name python-test ${IMAGE_NAME}:${IMAGE_TAG}

            # Wait for app to start
            sleep 3

            # Test API inside container using Python
            docker exec python-test python - << 'EOF'
import urllib.request
print(urllib.request.urlopen("http://localhost:5000").read().decode())
EOF

            # Stop container
            docker stop python-test || true
        """
    }
}


        stage('Trivy Scan') {
            steps {
                sh """
                    docker run --rm \
                        -v /var/run/docker.sock:/var/run/docker.sock \
                        aquasec/trivy:latest \
                        image ${IMAGE_NAME}:${IMAGE_TAG}
                """
            }
        }

        stage('List Images') {
            steps {
                sh "docker images | grep ${IMAGE_NAME}"
            }
        }
    }
}
