pipeline {
  agent {
    docker {
      image 'docker:24.0.7'
      args '-v /var/run/docker.sock:/var/run/docker.sock'
    }
  }

  environment {
    IMAGE_NAME = "python-demo"
    IMAGE_TAG  = "v1"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build Docker Image') {
      steps {
        sh """
          docker build -t ${IMAGE_NAME}:${IMAGE_TAG} docker-demo-python/
        """
      }
    }

    stage('Test Run Container') {
      steps {
        sh """
          docker run --rm -p 5000:5000 -d --name python-test ${IMAGE_NAME}:${IMAGE_TAG}
          sleep 3
          curl -s http://localhost:5000
          docker stop python-test
        """
      }
    }

    stage('Trivy Scan') {
      steps {
        sh """

